version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_crud
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: nest_crud
    ports:
      - '3000:3000'
    command: npm run start:dev

volumes:
  db-data: